name = "BeBot-Export"
description = "Export your bot data for import into other bots"
version = "0.1.1"
github = "Nadyita/BeBot-Export"
author = "Nadyita"
bot_type = "BeBot"
bot_version = ">=0.6.8 <0.8.0"
